### ISSUE TITLE
ar: cpu.o: file format not recognized

### ISSUE THREAD

**Issue by Rellotscrewdriver** [Arsenic-ATG/8085#49]
**without the cmake**
it seems doesn't recognize the object file(cpu.o) both in windows and linux
ar: cpu.o: file format not recognized

**with cmake**
I only tested this at your CMakeLists at /src directory. main.cpp is not recognized when generating the project
removing that from CMakeLists it generates and builds successfully. 
but it creates libcpu.a instead lib8080.a (judging by the last parameter of ar command)

both of the cases were tested on linux and windows with GCC and clang

**Comment by Arsenic-ATG** [comment]
> **without the cmake** it seems doesn't recognize the object file(cpu.o) both in windows and linux ar: cpu.o: file format not recognized

hmm, maybe try changing the order `ar rcs li8085.a cpu.o`

> 
> **with cmake** I only tested this at your CMakeLists at /src directory. main.cpp is not recognized when generating the project removing that from CMakeLists it generates and builds successfully. but it creates libcpu.a instead lib8080.a (judging by the last parameter of ar command)

Yes, that's an issue in documentation and build script, actually there are some changes I forgot to push before. 

> 
> both of the cases were tested on linux and windows with GCC and clang

Thanks for reporting this issue.
